services:
  redis:
    image: redis:latest
    container_name: mon-site-cosmetique-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - mon-site-cosmetique-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mon-site-cosmetique-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - mon-site-cosmetique-network
    depends_on:
      - db
      - redis
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mon_site_cosmetique
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PASSWORD=null
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis

  db:
    image: mysql:8.0
    container_name: mon-site-cosmetique-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=mon_site_cosmetique
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mon-site-cosmetique-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  dbdata:

networks:
  mon-site-cosmetique-network:
    driver: bridge 